server:
  port: 1000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka
    enabled: true
    register-with-eureka: false

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: broker-service
          uri: lb://broker-service
          predicates:
            - Path=/broker/**
          filters:
            - StripPrefix=1

  management:
    endpoints:
      web:
        exposure:
          include: "health,info"
    endpoint:
      gateway:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
